CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome_completo VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(20),
    profissao VARCHAR(100) DEFAULT NULL,
    cpf VARCHAR(14) DEFAULT NULL,
    endereco VARCHAR(100) DEFAULT NULL,
    profile_image VARCHAR(10000) DEFAULT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);